### ISSUE TITLE
Moving to extensible enum fields

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#11]
`Action` is a good example for this, as the previous way of defining an action was via `enum` values; now it is a complex object with a `resourceEffect` in addition to a name. There will thus be many locations where input `Action` types will need to be replaced with `ID`.

Which are the other fields which need to be de-referenced in this manner?

**Comment by pospi** [comment]
Others we need to discuss:

- `AgentRelationshipRole` & how `AgentRelationshipCategory` relates to the `roles` between `agent`s

**Comment by pospi** [comment]
Ok, we can skip the agent stuff. Action is the remaining one which needs some work in GraphQL.

Base requirements seem to be that (1) we should have all the `vf:action` types included as a base set, but (2) still allow extension. Ideally I think we would (3) also refer to actions in `EconomicEvent` et al by the name of the action (`use` etc) rather than some ID that needs to be de-referenced.

Currently we have (2) but neither of these other requirements. I think (3) is doable simply by recommending that the action verb be used as each action ID (done in eeb53a9). This would largely avoid the need for code to perform action lookups internally- the full details of an action (namely `resourceEffect`) are probably only needed when doing network planning type activities.

I've experimented with ways to do (1) in GraphQL, but all paths lead to cumbersome queries. So that probably ends up being a case of seeding a new system or hard-coding the backend implementation to return those types. As such, seems fine to close this issue.

**Comment by fosterlynn** [comment]
>Base requirements seem to be that (1) we should have all the vf:action types included as a base set, but 

Yes.  Sounds like you think that is solved by seeding or hard-coding, which at the moment is fine with me.

>(2) still allow extension.

That is actually unclear.  As of now, we don't really support extension, unless it gets defined through VF, because we don't have enough properties defined to make the whole thing machine-readable without hard-coding.  Being discussed here https://github.com/valueflows/valueflows/issues/487

>(3) also refer to actions in EconomicEvent et al by the name of the action (use etc) rather than some ID that needs to be de-referenced.

That would be great!

>the full details of an action (namely resourceEffect) are probably only needed when doing network planning type activities

You need it to increment or decrement the currentQuantity on the resource when an event comes through.  Unless resources are not instantiated, but re-calculated from events when returned; but I don't think this is reasonable for 99.9% of applications.
