### ISSUE TITLE
Suspected errata in `EconomicEvent`

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#12]
`resourceClassifiedAs` & `resourceConformsTo` don't feel as though they should be in the event records themselves, only in the input parameters when sending a resource creation event. Does that sound sensible?

Ah, just saw this comment: `should we have everything on a resource here also for events that create resources? or just on mutation definition?` ...so the answer is the latter (;

**Comment by fosterlynn** [comment]
Actually these 2 fields do need to be on EconomicEvent.  Often there is no actual inventoried resource, so one of those fields will be necessary.  Excmples are work, services, material items that aren't worth inventorying.

>Ah, just saw this comment: should we have everything on a resource here also for events that create resources? or just on mutation definition? ...so the answer is the latter (;

This is a different questions, answer noted.  This is what I did in OCP, but wasn't sure. :)

**Comment by pospi** [comment]
What do you think of my use of `IntendedResource` on the latest `feature/coherent-mutation-fields` branch? Basically anywhere where resources can be linked to seems to also want to be linkable to the *concept* of a resource?

**Comment by fosterlynn** [comment]
Some comments on this code, because seems like it needs some discussion rather than me doing something in the file.

```
union ProductionFlowItem = Process | Transfer | EconomicResource
```
If the above is for track and trace, let's add EconomicEvent. [edit: never mind, see below]

```
"""
When an `Intent`, `Commitment` or `EconomicEvent` is set to provide some
`EconomicResource`s, but the exact resources to service are still unknown, or
(in the case of `EconomicResource`) not inventoried.
In these cases, an `IntendedResource` can be used to indicate the type
of resource to be provided later.
"""
type IntendedResource {
  classifiedAs: [String]
  conformsTo: ResourceSpecification
}

"""
Specifies an intention to provide a type of resource in some interaction
context (usually an `Intent`, `Commitment` or `EconomicEvent`)
"""
input IIntendedResource {
  classifiedAs: [String]
  conformsTo: ID # ResourceSpecification
}
```
So for IntendedResource, I think that concept is covered already by EconomicResource, resourceClassifiedAs, and resourceConformsTo.  For Intents and Commitments, usually there is not yet an EconomicResource that can be referenced, and won't be until the EconomicEvent.  The only time you would see an actual EconomicResource in the planning layer is if there is some specific unique item or maybe a used item.  But if you are for example ordering something, or planning to consume something in a process, you are only talking about the type of resource, not any particularly identified resource.  And you wouldn't have occasion as far as I can think of to at any point replace the type definition with an EconomicResource reference.  That will happen as EconomicEvents are created, and you will know the EconomicResource if there is one at that point.

And Intents, Commitments, and EconomicEvents all can reference any of those 3 representations of resource-ness.

**Comment by fosterlynn** [comment]
>>union ProductionFlowItem = Process | Transfer | EconomicResource

>If the above is for track and trace, let's add EconomicEvent.

Never mind!  I see now you are using that only on EconomicEvent, sorry about that.  Good as it is.

**Comment by fosterlynn** [comment]
>So for IntendedResource, I think that concept is covered already by EconomicResource, resourceClassifiedAs, and resourceConformsTo.

I see that the classification and specification reference properties are not in EconomicEvent. We'll need to get them back in too - and wherever else they were removed from.

**Comment by pospi** [comment]
> I see that the classification and specification reference properties are not in EconomicEvent. We'll need to get them back in too - and wherever else they were removed from.

I didn't remove them- I replaced them with the `IntendedResource` struct. My intention was just to encapsulate those fields in the records to which they relate- rather than having large, flat structures with heaps of properties it made sense to me that things related to types of resources be grouped into a sub-struct. But if it doesn't feel right to you and you would rather have event/commitment/intent include the fields at the top level, I can revert it easily.

**Comment by fosterlynn** [comment]
>My intention was just to encapsulate those fields in the records to which they relate- rather than having large, flat structures with heaps of properties it made sense to me that things related to types of resources be grouped into a sub-struct. But if it doesn't feel right to you and you would rather have event/commitment/intent include the fields at the top level, I can revert it easily.

Here is a perhaps complicated answer.  Bottom line, I think we should revert it for now. 

But I also like the idea, and we have even toyed with something like that in the past.  The reason is not so much that it will become an EconomicResource eventually, because many won't, and most won't while they are an intent or a commitment. It is because those 3 properties, or one or two of them, describe the bigger conceptual "resource-y" thingy-ma-bob that the event references, and it would be good to call that out.  And I agree with your statement about avoiding large flat structures.

On the other hand, it requires a new term, and to try to keep different technologies compatible using VF, the structure and its name should go through the VF processes first imo.  And we have quite a backlog of core issues to finish discussing.  And they take a very long time, as standard writing tends to do.

On the other other hand, we can in controlled ways try out things in the implementations that are going on, and bring back the results to VF with recommendations.  Better an actual implementation to test something than lots of yaml examples done by hand, although those certainly have their place.

**Comment by fosterlynn** [comment]
@pospi 

>On the other hand, it requires a new term, and to try to keep different technologies compatible using VF, the structure and its name should go through the VF processes first imo. And we have quite a backlog of core issues to finish discussing. And they take a very long time, as standard writing tends to do.

P.S. I might float it over in VF to see if by chance we do actually have some agreement on that idea and could accomplish it relatively quickly.  I'm thinking it would encompass all 3 properties though.  Does that make sense to you?

**Comment by pospi** [comment]
Reverted! (: To be continued one day, maybe...
