### ISSUE TITLE
Standardise on `Id` suffix for fields / mutations, or same name?

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#13]
I think this basically impacts how much boilerplate we have to write in every implementation vs. how much "glue" code and serialisation logic.

Do we take inputs in mutations like this?

```
   input EconomicEventCreateParams {
      inputOfId: ID
```

...or like this?

    input EconomicEventCreateParams {
      inputOf: ID

I lean towards the latter, as the `ID` type essentially implies a reference anyway. You would basically need to create helpers in the app backend to check an array of fields for referential integrity before saving input; and similar helpers for retrieving referenced objects when returning data back out.

**Comment by fosterlynn** [comment]
I'm fine with your recommendation, don't feel like I have the experience to say.  Do we know if there is some level of standard on that for graphql people?

(I used the inputOfId because I was in python/django, and objects are getting passed around all the time, so I by habit wanted the object itself to look different in the code than an integer, or in this case a string, id.)

**Comment by pospi** [comment]
I'm going to go with the "no ID suffix" option, because it keeps things in the terser format (which seems generally preferred in gQL-land), plus the `ID` type clearly indicates what you're passing or returning.
