### ISSUE TITLE
Confirming mutation / reference field behaviours

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#14]
This to confirm what is currently implemented so as to ensure all create & update methods are accurate.

**`EconomicEvent`**

- `under`, `fulfills`, `satisfies`, `appreciationFor`, `track` & `trace` are the only readonly fields which can not be set when creating or updating an event.
- `affectsSome` is new. It's a name I thought worked for defining an `IntendedResource`, which is a new struct I created to encapsulate that bit of behaviour. I have merged everything to master (it all compiles & executes now) so you can take a look at this and provide any name changes you think are necessary.

...more to come... doing this sporadically...

**Comment by fosterlynn** [comment]
>under, fulfills, satisfies, appreciationFor, track & trace are the only readonly fields which can not be set when creating or updating an event.

Of those, `track` and `trace` are readonly.  The rest will need to be set in some way.  `under` references an existing Agreement (atm) so would be part of the EconomicEvent mutation.  `appreciationFor` references an existing EconomicEvent, so also would be part of the mutation. `fulfills` and `satisfies` both need to create a new instance of Fulfillment or Satisfaction, which will have a reference to the Commitment or Intent fulfilled or satisfied.  How is the best way to do that?  Gut feel, I'd like to have that as part of the EconomicEvent mutation because that is the only trigger that would create one of those.  Sort of like we are doing for EconomicResource.  Not sure about update, but thinking that could be direct to Fulfillment or Satisfaction without any change to the EconomicEvent.  But as usual, I don't know what would be the best practices or standards for that sort of thing in graphql?

>I have merged everything to master (it all compiles & executes now) so you can take a look at this and provide any name changes you think are necessary.

Will do, thanks.

>doing this sporadically...

me too.... :)

**Comment by fosterlynn** [comment]
Informational note:  In some cases, like both fulfillment and satisfaction, there is no structure in OCP that matches what is in VF.  So the graphql you see in OCP may be deficient - sometimes I hobbled it together so it looks like there is a VF compliant structure, sometimes was not able to.

**Comment by pospi** [comment]
I don't think the decisions you're talking about RE editability of `under` et al have much to do with GraphQL, and everything to do with how we maintain the integrity of the system. If `fulfills` and `satisfies` were simple associations I think it would make sense to do them via the `EconomicEvent` entrypoints. But since they have additional data, my gut feeling is they need to be managed as their own separate objects with their own CRUD routes. Otherwise, the logic for handling them via indirect structs gets messy quickly.

As an added overarching decision, does it make sense that all records should be fully editable, basically to account for data entry errors? Should one potentially have to provide a note when editing records to indicate the reason for the change?

**Comment by fosterlynn** [comment]
>But since they have additional data, my gut feeling is they need to be managed as their own separate objects with their own CRUD routes. Otherwise, the logic for handling them via indirect structs gets messy quickly.

I can go with that.  Puts a bit more responsibility on the client I guess.  But simpler for us.  In some ways simpler for the client, in some ways another requirement.

Looking more to the future architecture, I'm going to start an issue and reference this one - I think we want to have complete record of all CRUDing anyhow, no more just doing it directly.  [edit - Maybe it wouldn't affect this graphql reference, hmmm.  We can talk about it in the actual projects,and I won't start an issue here.]

**Comment by fosterlynn** [comment]
In terms of the original list above, `appreciationFor` is like `fulfills` or `satisfied`, so can follow that decision.  `under` though is not, it is just like `provider` or whatever, just a foreign key type of reference.

**Comment by pospi** [comment]
Happy with these for now, most of them follow a pretty predictable pattern. Will open separate issues for any further queries.
