### ISSUE TITLE
setup a build process & tag alpha release on NPM

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#32]
At the moment I have https://github.com/holo-rea/holo-rea linked with this repo via git submodules, and that's not ideal from a code complexity perspective. The real solution is to treat `vf-graphql` as "stable" and start deploying releases that we (and others) can link to idiomatically.

The most awkward part of this is that we want raw `*.gql` schema files available for import by other modules, but we also want versions where the schema string is present in memory *at interpretation time*; so you can do a simple `require` and not have to mess around with `fs.readFile` and/or webpack loaders. That means we need to release two versions of the source (one as hardcoded strings in nodejs modules, the other as flat source files); which means we have to generate the former from the latter. We want the native authoring format for schemas to be GraphQL, to assist with editor syntax highlighting & code completion.

**Comment by pospi** [comment]
Build process completed- see last few commits. Now we just need to decide whether it's time to start publishing to a package registry or not.

**Comment by pospi** [comment]
Note the reason to move on this was for the `vf-graphql` related parts of https://github.com/holo-rea/holo-rea/issues/14. With the build system done, the way this module is integrated with the HoloREA project (via git submodules) is perfectly adequate for the forseeable future (it only gets complicated if you're working on both projects at once- contributors like @sqykly who have not been a part of the GraphQL repo shouldn't have to think about it).

So, there's no need to see this as an urgent issue until projects using it start to want to publish fixed versions; then we should make the final moves to setting up an NPM account, versioning and packaging things up.

Related question: what's the correct starting version for this? Is there an existing VF version we should sync with or does `vf-graphql` just start at `1.0.0-beta1`?

**Comment by fosterlynn** [comment]
>Is there an existing VF version we should sync with

I don't know the answer, but VF is at .2 (will be awhile before we get to 1.0)  :relaxed:

**Comment by fosterlynn** [comment]
>Is there an existing VF version we should sync with

Further thought on this.  I don't think we need to stay completely in sync with VF.  At the same time I think 1.0.0-beta1 is wildly optimistic.  There are a number of things just missing (for example budgeting, community analysis, a lot of Intent); and there will be changes (for example a re-do of transfer).

I think we could transition vf-graphql along its own releases driven by the rhythms of the dev and user communities.  For example, when we are ready to set something that will be used for this initial group of HoloREA users, like when we are ready to put it into the HoloREA framework code, let's do a numbered release with the best we have at that moment.  Then we can use it there until we have gone through a cycle of code and learning with them, even if it moves to further releases during that time, driven either by other user communities or by changes in VF.  I do foresee that vf-graphql could be ahead of VF during some periods, as a mechanism of getting feedback back into VF, and just because some user groups need something that isn't done in VF.

At the same time, it is really kind of part of VF too, and in the end should totally reflect VF.

**Comment by pospi** [comment]
> `1.0.0-beta1` is wildly optimistic

Fair enough, I'm thinking semver... maybe I mean `0.1.0-beta1`. "Beta" should just mean "no more breaking API changes expected", and I'd hope we can get at least that far.

> we could transition vf-graphql along its own releases driven by the rhythms of the dev and user communities

Ok, sounds good. I might as well just close this then and let it emerge naturally as other integrators start showing up (:
