### ISSUE TITLE
Add ProcessSpecification.conformingProcesses

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#63]
There needs to be a way to query all `Processes` via the specification that defines their behaviour, in order to locate all processes of a given type.

The `conformingProcesses` need to be filterable by many criteria, TBC...

**Comment by fosterlynn** [comment]
A note on ProcessSpecification.  For people who don't use recipes, the main use of ProcessSpecification I can think of is for "workflow" sequences of processes, where the same resource is input and output of a sequence of processes.  The example we are most familiar with is translation: translating, editing, proofreading, formatting.  That kind of thing, where a document would be passed through the different stages.  The stages would be defined by ProcessSpecifications.

This is to give you info to see where it might fit into the priorities, since not every group will need this type of workflow process sequencing.

**Comment by pospi** [comment]
I logged this one for a need to be able to "find all these types of processes". In this particular use-case it is things like retrieving all the information about "the deliveries we planned to fill this week". I figured an easy way of achieving that was on querying `Process` with a `ProcessSpecification` filter and a time range.

I can see that there might be reasons that `Process` isn't seen as a primary query entrypoint for these kinds of supply chain & management queries, though. If there's a pitfall in the approach I'm outlining here and a more idiomatic means of making such queries (I would assume, if anything, that they might center more on `EconomicEvent` than `Process`); it would be good to have some documentation to assist with understanding that somewhere if there isn't already.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/63.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
