### ISSUE TITLE
Agree on API for agent commitment & intent queries

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#73]
The older spec has `Agent.commitmentsMatchingSkills` and `Agent.agentCommitments(latestNumberOfDays: Int)`.

Wondering which commitment types we should be filtering on here and loading for representing potential & active commitments?

**Comment by fosterlynn** [comment]
>Agent.commitmentsMatchingSkills

This seems like too specific a query to support right now, but @ivanminutillo what do you think?  Also, it would probably be intents, not commitments now (in old code we used commitments without committed agents since we didn't have intents).  If we do it on Intents, we could make it a more generic matching query, something that matches resourceConformsTo and/or resourceClassifiedAs, matching to what an agent has done previously, or we could use the new `primaryAccountable` on an economic resource.... Probably this whole thing needs more thought, matching logic is a whole feature with some complexity.

>Agent.agentCommitments(latestNumberOfDays: Int)

I think we probably need a generic query for all related commitments, so that is scope, provider, or receiver.  But also, I'm thinking this could be all commitments where the agent is the provider, i.e. the agent that has committed - so maybe a parameter for that?  And a useful parameter could also be `finished`.  Not sure about the number of days, seems like that was sort of a hack that we didn't actually use?  @ivanminutillo ?

>potential & active commitments

Do you mean commitments that have been partially or fully fulfilled?  Or potential in the sense it is an Intent, not a Commitment in VF?

**Comment by pospi** [comment]
I'm all for pushing matching logic into future exploration, that wasn't what I was intending on getting invested in with these first passes at a standard API.

> we could make it a more generic matching query, something that matches resourceConformsTo and/or resourceClassifiedAs

Agree. And I think the best thing to do here is for this to be a nonstandard extension or app-level feature- eg. having storage for an agent's list of preferred work skills to pass to such an API to make this kind of query.

I think I do mean potential in the way you said above, so I changed the issue title to reflect. No `Intent` API in shroom is just an artifact of not having those data types at the time, then.

Based on the pass I made at event, here's a first suggestion for these two:

```gql
enum AgentFlowRelationshipType {
  PROVIDER
  RECEIVER
}
enum ItemFinishedStatus {
  UNFINISHED
  FINISHED
}
input agentCommitmentSearchParams {
  searchString: String
  startsOnOrBefore: DateTime
  startsOnOrAfter: DateTime
  endsOnOrBefore: DateTime
  endsOnOrAfter: DateTime
  dueOnOrBefore: DateTime
  dueOnOrAfter: DateTime
  involvementType: AgentFlowRelationshipType
  finished: ItemFinishedStatus
  accountingScopeIn: [ID!]  # matches agents inScopeOf/provider/receiver
  actionIn: [ID!]
  inputProcessIn: [ID!]
  outputProcessIn: [ID!]
  affectedResourceIn: [ID!]  # this would match toInventoriedResource as well?
  resourceSpecificationIn: [ID!]
  resourceClassificationIn: [URI!]
  realizedAgreementIn: [ID!]
  locationIn: [ID!]
  fulfilledByEventIn: [ID!] # these should match on the flow record IDs, not the relationship records?
  satisfiesIntentIn: [ID!]
}
input agentIntentSearchParams {
  # same as for Commitment, actually...
  # - except no `realizedAgreementIn`
  # - and `satisfiedByCommitmentIn` & `satisfiedByEventIn` instead of `fulfilledByEventIn` & `satisfiesIntentIn`
}
```

**Comment by pospi** [comment]
Closing this issue to defer it for now; we'll approach these questions in a much more piecemeal manner.
